title: My Jekyll Site
description: A basic site built entirely on the web.
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# This section controls the navigation menu
header_pages:
  - index.md
  - about.md
  - gallery.md
  - blog.md
